"""add_documents_chat

Revision ID: 87341c9d5c7b
Revises: d0f084dd99d6
Create Date: 2025-10-09 21:13:17.428953+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87341c9d5c7b'
down_revision: Union[str, Sequence[str], None] = 'd0f084dd99d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('document_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'document_ids')
    # ### end Alembic commands ###
