"""create user, chat, message tables

Revision ID: f5f65f6ed62a
Revises:
Create Date: 2025-10-08 21:54:35.734990+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.domain.chat.models import *
from app.domain.user.models import *
from app.domain.message.models import *

# revision identifiers, used by Alembic.
revision: str = "f5f65f6ed62a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
